[project]
name = "pydantictooluse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.10",
    "pydantic-ai>=1.1.0",
]
