[project]
name = "graph"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "kuzu>=0.11.3",
    "langchain>=0.3.27",
    "langchain-community>=0.3.31",
    "langchain-ollama>=0.3.10",
    "ollama>=0.6.0",
]
