[project]
name = "infinite-memory-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.9",
    "chromadb>=1.0.20",
    "markdown>=3.8.2",
    "unstructured>=0.18.13",
]
