[project]
name = "ollamaexamples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kuzu>=0.11.0",
    "langchain>=0.3.26",
    "langchain-community>=0.3.27",
]
